# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 765258ee60ef5447cb8e43df6760c9d17223c854b99eded58f8dfacfead1e5a8cca1be9d7a9fef08d9508329962e120e3b72513e713cda219dbf265bf19640d5

test:
  secret_key_base: feff916fef3cddb1d8970080c807498192ad9ef9adf14d27e7ec8a4dc22b7020853b52b12e7645f9fbdda58a3dc60867fc1fdaf5f0cb678787d13c02468f999c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
